desired_checklist_of_anonymous_sources = [
    # anonymous sources/groups of sources
    "officials", "experts", "authorities", "analysts",
    "scientists", "forecasters", "critics", "person",
    "democrats", "opponents", "police", "woman",
    "spokesman", "spokeswoman", "economists", "witnesses",
    "legal experts", "rights groups", "officers", "prosecutors",
    "pilot", "environmentalists", "administration officials", "people",
    "government scientists", "investigators", "neighbor", "plaintiffs",
    "environmental groups", "residents", "white house officials", "proponents",
    "environmental activists", "retailers", "iowa couple", "uber driver", "driver",
    "villagers", "volunteer", "a higher education trade group", "gun control groups",
    "gun rights advocates", "mining watchdog groups", "starbucks spokesman", "target spokeswoman",
    "gun control experts", "local media outlets", "israel", "provincial environmental officials",
    "marianne williamson's state director", "supporters", "local ’s boss", "researchers",
    "kathleen sgamma", "oil experts", "taciturn fishermen", "mississippi official",
    "auditors", "television news", "speculation", "insurance companies",
    "reports", "fed policy makers", "big creek residents", "new england ’s seafood industry",
    "both sides", "readers", "protesters", "environmental officials",
    "union officials", "transit officials", "some workers", "election officials",
    "european scientists", "local news media", "restaurant", "employee",
    "white house official", "other men", "head of the vote auditing company", "some men",
    "companies", "kenya's top politicians", "justice department", "taxi companies",
    "news reports", "opposition", "lawmakers", "seismologists",
    "associated press reporter", "the city manager", "company insiders",
    "weather officials", "kansas officials", "republicans", "local residents",
    "party official", "retired lawyer", "climate change denialists", "government officials",
    "fireman", "enza", "a republican operative", "surrogates",
    "local officials", "developers", "meteorologists", "defenders",
    "dealers", "enthusiasts", "a gun owner", "sellers",
    "gun salesman", "federal government", "dispatcher", "party strategists",
    "one house republican", "other republican", "climate experts", "global carbon project",
    "engineers", "911 recording", "advocates", "defendents lawyer",
    "salvage experts", "facebook spokewoman", "letter", "representative",
    "bill's sponsors", "robstown police officials", "government ’s statistics bureau",
    "puerto rico electric power authority", "power authority", "authority",
    "company official", "crew members", "activists", "protestors", "native americans", "environmental activists",
    "native american leaders", "tribal leaders", "leaders", "consumer protection advocates", "organizers",
    "election experts", "colleague of reid hoffman", "italian news media", "another man",
    "many brazilians", "photojournalist", "administration official", "unnamed",
    "city officials", "one man", "several people", "chinese court",
    "polk county sheriff ’s office spokeswoman", "european leaders", "lauren bonner", "four people",
    "women", "customers", "senior official", "television interview",
    "israeli security officials", "nagashiki shipping representative", "a pentagon spokeswoman", "police spokeswoman",
    "policy makers", "political rivals", "political opponents", "the mauritian authorities",
    "cbs executives", "safety experts", "conservative media outlets", "cbs staff members",
    "cbs staff member", "local prosecutor ’s office", "demonstrators", "company officials",
    "asiana officials", 'Laotian diplomats', 'diplomats', 'company', 'pilots ’ union', 'lawyers',
    "campaign",
    # hacks
    'Stripe', 'The Nation', 'The Atlantic', 'Salon'
    ## PARC3 anon sources
    "investors", "president", "people", "chairman", "officials", "analysts",
    "vice president", "director", "traders", "analyst", "employees", "workers",
    "executive", "chief executive officer", "members", "executives", "spokesman", "managers",
    "shareholders", "customers", "manager", "holders", "leaders", "directors",
    "investor", "lawyers", "management", "judge", "man", "head",
    "group", "children", "men", "family", "leader", "brokers",
    "women", "pilots", "official", "company", "consumers", "buyers",
    "attorney", "partner", "economist", "economists", "member", "students",
    "team", "woman", "force", "producers", "consultant", "staff",
    "chief operating officer", "regulators", "lawmakers", "trader", "dealers", "victims",
    "bankers", "secretary", "clients", "editor", "individuals", "owners",
    "farmers", "voters", "lawyer", "chief", "residents", "researchers",
    "scientists", "public", "parents", "forces", "families", "blacks",
    "experts", "person", "professor", "specialists", "spokeswoman", "adviser",
    "defendants", "reporters", "colleagues", "prosecutors", "judges", "chief financial officer",
    "critics", "broker", "audience", "representatives", "politicians", "wife",
    "candidates", "sources", "authorities", "patients", "taxpayers", "vice chairman",
    "attorneys", "senators", "owner", "founder", "consultants", "players",
    "police", "groups", "mother", "observers", "population", "father",
    "participants", "customer", "users", "friend", "speculators", "writer",
    "officer", "agents", "advisers", "officers", "counsel", "son",
    "subscribers", "leadership", "citizens", "activists", "child", "husband",
    "author", "friends", "viewers", "machinists", "supporters", "engineers",
    "governor", "whites", "rebels", "community", "teachers", "producer",
    "mayor", "banker", "specialist", "doctors", "client", "worker",
    "readers", "partners", "opponents", "financier", "couple", "makers",
    "successor", "legislators", "associates", "spokesman", "aide", "businessmen",
    "publisher", "employee", "respondents", "professionals", "candidate", "student",
    "farmer", "personnel", "buyer", "staffers", "individual", "strategist",
    "foreigners", "visitors", "fans", "tourists", "troops", "treasurer",
    "brother", "agent", "holder", "underwriters", "sellers", "passengers",
    "operators", "spokesman", "advocates", "crowd", "kids", "characters",
    "bondholders", "expert", "defendant", "developer", "aides", "ringers",
    "principal", "shareholder", "teams", "parties", "doctor", "stockholders",
    "character", "drivers", "analyst", "reporter", "actor", "congressman",
    "witnesses", "jurors", "dealer", "user", "minister", "couples",
    "entrepreneur", "majority", "raider", "plaintiffs", "developers", "ministers",
    "brothers", "negotiators", "arbitragers", "protesters", "salespeople", "researcher",
    "adjusters", "investigators", "guy", "mediator", "delegation", "representative",
    "adults", "pilot", "environmentalists", "witness", "commuters", "audiences",
    "veteran", "boss", "bureaucrats", "prime minister", "actors", "businessman",
    "senator", "conservatives", "writers", "diabetics", "journalists", "humans",
    "teacher", "communities", "dictator", "star", "columnist", "player",
    "borrowers", "authors", "generation", "salesman", "minorities", "figure",
    "households", "regulator", "refugees", "commissioner", "demonstrators", "press",
    "prosecutor", "conferees", "class", "artists", "boys", "chief investment officer",
    "homeowners", "presidents", "master", "host", "daughter", "singer",
    "beneficiaries", "report", "administrator", "salesmen", "assistant", "baby",
    "planners", "outsiders", "growers", "legislator", "allies", "lobbyists",
    "critic", "staffs", "artist", "guests", "spouses", "constituents",
    "governors", "entrepreneurs", "editors", "criminals", "relatives", "accountants",
    "shah", "journalist", "victim", "middlemen", "girl", "guerrillas",
    "attorney general", "fan", "crew", "baby boomers", "proponents", "congressmen",
    "liberals", "cast", "persons", "bosses", "counterparts", "lobbyist",
    "scholars", "travelers", "financiers", "reformers", "justices", "designer",
    "soldiers", "scientist", "activist", "architects", "principals", "reader",
    "supervisors", "guys", "who", "backers", "politician", "engineer",
    "winner", "folks", "hunters", "designers", "youth", "investigator",
    "caller", "diplomats", "subscriber", "elderly", "males", "insiders",
    "neighbors", "spokeswoman", "opponent", "analyst", "architect", "trader",
    "listeners", "fellow", "crews", "announcer", "ambassador", "predecessor",
    "chief economist", "playwright", "speaker", "general", "spy", "figures",
    "supervisor", "clerk", "wives", "volunteers", "attendants", "pros",
    "department", "strategists", "analysts", "sponsor", "driver", "hero",
    "enemies", "source", "arbitrator", "hacker", "co-author", "citizen",
    "nominees", "daughters", "comptroller", "seller", "bikers", "poor",
    "physicians", "anti-abortionists", "taxpayer", "operator", "technicians", "beings",
    "watchers", "billionaire", "sister", "talent", "junk-holders", "shoppers",
    "girlfriend", "newcomers", "actress", "guards", "scholar", "nurses",
    "applicants", "franchisees", "consumer", "spouse", "merchants", "widow",
    "models", "yuppies", "boy", "patient", "judge", "communists",
    "negotiator", "passenger", "claimants", "grower", "enthusiasts", "guard",
    "champion", "purchasers", "knight", "parent", "chancellor", "chefs",
    "faculty", "astronauts", "furriers", "intellectuals", "foreign minister", "bank",
    "callers", "others", "co-chairman", "veterans", "counterpart", "replacement",
    "planner", "smokers", "pickers", "managing director", "raiders", "educators",
    "associate", "heads", "sons", "deputies", "subjects", "official",
    "miners", "stars", "positions", "generations", "dependents", "king",
    "chairmen", "indexers", "administrators", "market-makers", "company spokesman", "filing",
    "liberal", "ally", "mom", "aliens", "homeless", "creator",
    "companion", "trustee", "stockbrokers", "skeptics", "hosts", "butler",
    "prisoner", "hostages", "dictators", "traffickers", "card holders", "coordinator",
    "riders", "publicist", "prisoners", "duo", "spokesmen", "policyholders",
    "followers", "collectors", "minors", "sociologist", "survivors", "nominee",
    "framers", "appropriators", "an analyst", "inspector", "visitor", "trustees",
    "immigrants", "detective", "suit", "professors", "prospects", "gangs",
    "chemists", "foes", "novelist", "creditors", "graduates", "defenders",
    "treasury secretary", "inspectors", "panel", "moderates", "justice", "investment bankers",
    "body", "practitioners", "youngsters", "bidders", "number", "vicar",
    "servants", "inventor", "bureaucrat", "marketers", "industry executives", "undersecretary",
    "an official", "losers", "naczelnik", "ringer", "unitholders", "patron",
    "dissidents", "managements", "composer", "authority", "association", "subordinates",
    "deputy", "deputy mayor", "examiners", "skier", "proponent", "clientele",
    "adjuster", "peasant", "speculator", "government officials", "group", "secretary general",
    "sources", "officials", "successors", "band", "fliers", "clerks",
    "mankind", "retirees", "performers", "competitors", "depositors", "correspondent",
    "guide", "study", "rival", "membership", "musicians", "vice presidents",
    "spectators", "capitalists", "nurse", "masters", "stockholder", "physician",
    "handlers", "voter", "tycoon", "insurgents", "classes", "roommate",
    "commissioners", "skiers", "tenants", "accountant", "insured", "strikers",
    "dissenters", "masseurs", "thief", "targets", "gang", "promoters",
    "dentists", "secretaries", "thieves", "outsider", "constituency", "franchisers",
    "spokeswoman", "opposition", "poet", "landowners", "physicist", "hikers",
    "masses", "target", "civilians", "work force", "symbol", "robbers",
    "acquirer", "company", "bidder", "scammers", "researchers", "homosexuals",
    "insider", "advocate", "delegates", "schoolteacher", "recipients", "examiner",
    "distributors", "psychoanalyst", "landlords", "prostitutes", "surgeon general", "heir",
    "grandchildren", "confidant", "genius", "neighbor", "contractors", "philosophers",
    "pitchers", "ballplayers", "uncle", "diplomat", "folk", "killers",
    "pianist", "motorist", "inspector general", "plaintiff", "classmates", "readership",
    "institute", "cooks", "realists", "traveler", "white", "name-droppers",
    "recruiter", "vacationers", "chemist", "pitcher", "handful", "ladies",
    "magistrate", "minority", "party", "stranger", "companies", "prosecutor",
    "marketer", "suspects", "filers", "enemy", "lover", "statement",
    "forecasters", "composers", "money managers", "sailors", "butcher", "girls",
    "inmates", "underwriter", "curator", "reformer", "heirs", "hitter",
    "executive", "employer", "historians", "co-chief executive officer", "sponsors", "murderer",
    "constituent", "psychologist", "stock pickers", "soldier", "corps", "commanders",
    "graduate", "peoples", "auditors", "emigres", "youths", "participant",
    "fund managers", "grandfather", "spies", "theorist", "policeman", "premier",
    "pioneers", "resident", "boosters", "pack", "countrymen", "delegate",
    "fishermen", "auditor", "fools", "gentlemen", "mentor", "machikin",
    "masseuse", "czars", "suppliers", "lady", "seniors", "agency",
    "survivor", "rulers", "ex-President", "subgroups", "policewoman", "vendor",
    "spirit", "co-owner", "controllers", "populations", "mothers", "commentators",
    "colleague", "adversary", "breed", "co-head", "offenders", "gurus",
    "prostitute", "rangers", "laborers", "captain", "motorists", "photographers",
    "lecturer", "terrorists", "balloonists", "addicts", "couriers", "diners",
    "patrons", "suckers", "courier", "firefighters", "chef", "directors",
    "mayors", "stonemason", "exporter", "kidnapper", "dwarf", "secretary-general",
    "coaches", "pollsters", "innocents", "programmers", "payers", "superiors",
    "letter", "coach", "appointee", "scores", "co-founders", "kid",
    "senior", "source", "teen-ager", "pimp", "market", "race",
    "doomsayers", "camps", "comedian", "prince", "violinist", "cousin",
    "elitists", "trust", "an operator", "cronies", "traders", "musician",
    "freshmen", "pushers", "swimmer", "firm", "adult", "monster",
    "sergeant", "fanatics", "soloist", "alumni", "federal judge", "constituencies",
    "interviewer", "ghostbusters", "major", "fund-raiser", "publishers", "organizer",
    "chief information officer", "neurologist", "co-manager", "fund officials", "naysayers", "guinea pigs",
    "pedestrians", "society", "libertarians", "defense", "testers", "elders",
    "correspondents", "neurosurgeon", "right-to-lifers", "fathers", "thinker", "kinds",
    "propagandists", "refugee", "spokesperson", "fugitives", "dentist", "arbitrager",
    "czar", "accusers", "envoy", "buffs", "cyclist", "housewife",
    "equestrians", "pollster", "superintendent", "juror", "rollers", "sociologists",
    "psychologists", "organizers", "mate", "tax-writers", "director general", "council",
    "cognoscenti", "lawyers", "entertainers", "newspaper", "protege", "passers-by",
    "roustabout", "holdouts", "drillers", "salesperson", "doubters", "industrialists",
    "conservative", "promoter", "profiteers", "contractor", "feminists", "runners",
    "librarian", "deputy president", "bartenders", "celebrities", "renters", "shadow",
    "contacts", "senior administration official", "pair", "monitor", "evaders", "contestant",
    "agencies", "schoolchildren", "nationalists", "contributors", "staffer", "experts",
    "help", "colonel", "peasants", "soul", "liar", "villagers",
    "crooks", "haole", "factions", "occupant", "souls", "commander",
    "breeder", "breeders", "weepers", "eye", "heroes", "wardens",
    "proprietors", "greats", "fetus", "trainer", "crook", "sharecroppers",
    "elite", "aunt", "pirates", "government", "luminaries", "currency analysts",
    "baseman", "takeover expert", "conspirators", "ranchers", "father-in-law", "batter",
    "sucker", "instructors", "maid", "lawmaker", "fundamentalists", "peers",
    "laureate", "thug", "analysts", "hawk", "enforcers", "exchange officials",
    "psychiatrist", "lovers", "institutions", "personalities", "maker", "gardener",
    "comrades", "congressional aides", "infants", "fifth graders", "recruits", "performer",
    "clarinetist", "set", "listener", "beneficiary", "buddy", "globalists",
    "tenor", "monetarists", "company officials", "gambler", "widows", "purists",
    "aide", "translator", "son", "bureau", "races", "bank spokesman",
    "favorite", "killer", "husbands", "spectator", "vicars", "club",
    "attendees", "clergyman", "orphans", "disabled", "magnate", "centenarians",
    "market analysts", "functionaries", "bachelor", "narrator", "lieutenants", "faithful",
    "commentator", "executives", "guru", "gunmen", "creators", "native",
    "revolutionary", "homemaker", "idealist", "grandmother", "relative", "tippee",
    "tipper", "gigolo", "dropouts", "mechanics", "haulers", "industry analysts",
    "anti-programmers", "superintendents", "celebrity", "cartoonist", "geeks", "radicals",
    "marketeers", "nerds", "side", "pediatrician", "salarymen", "mobster",
    "maverick", "academics", "waiters", "emcee", "kingpins", "billionnaire",
    "whip", "magistrates", "queen", "alcoholics", "hitters", "apologists",
    "speakers", "bears", "extremists", "painter", "receptionist", "rivals",
    "adjudicators", "adjudicator", "clan", "deputy director", "cowboys", "pilots",
    "teen-agers", "astronomer", "abortionist", "short-sellers", "ministry", "protestors",
    "operatives", "numbers", "blessing", "handicapped", "stockbroker", "chauffeur",
    "champions", "housekeeper", "dean", "company spokeswoman", "traditionalists", "babies",
    "hospital officials", "panel", "ombudsman", "defender", "appointees", "elites",
    "his wife", "narrator", "plotters", "inheritor", "employers", "co-sponsors",
    "dissident", "friend", "mathematician", "masseur", "registrants", "historian",
    "non-communists", "vice minister", "bodies", "stalwarts", "traders", "cherubs",
    "earners", "chief credit officer", "policy-makers", "terms", "other", "vice-president",
    "news-weekly", "individuals", "superstars", "contenders", "most big computer makers", "chiefs",
    "stowaway", "linebackers", "eaters", "survey", "dolt", "",
    "connoisseur", "direct-mail advertising firms", "gangsters", "government-appointed experts", "store owner", "flame",
    "stylist", "film-maker", "donors", "designees", "repression", "ambitious yuppies",
    "couch potatoes", "prospect", "pope", "marketing experts", "boxer", "capitalist",
    "squadron", "in-law", "pre-Reagan", "madman", "weatherman", "senders",
    "consumer researchers", "co-host", "big brokerage firms", "companies", "goddess", "exchange",
    "natives", "pro-Noriega", "malcontent", "outlanders", "auto executives", "commercial",
    "anti-outsider", "leakers", "out-of-staters", "attitudes", "globalist", "monetarist",
    "females", "securities industry officials", "network spokesman", "adepts", "sultan", "holdovers",
    "chief administrative officer", "classmate", "mavens", "supply-sider", "president-elect", "vicitims",
    "sycophants", "research director", "juniors", "mediators", "exploiters", "elements",
    "middle", "stalwart", "fund executives", "scout", "tailback", "executor",
    "ex-player", "hoarder", "stepmother", "ex-employer", "government figures", "sort",
    "distillers", "scribblers", "jewelers", "liquidator", "nemesis", "president",
    "decision-makers", "administration officials", "assistants", "criticisms", "count", "squads",
    "flanker", "decedent", "court", "securities firm", "bruddah", "brah",
    "press secretary", "houseman", "bride", "great mystery novelist", "champ", "banks",
    "diaries", "lineman", "provisions", "temps", "renter", "sub-underwriters",
    "brats", "offspring", "mutual fund executives", "fund groups", "person", "fund specialists",
    "metalworkers", "pushover", "zealot", "underdog", "shvartze", "former executive",
    "executive", "subordinate", "chief executive", "pro-Reagan", "gentlelady", "bystanders",
    "gentleladies", "theologian", "anti-Somoza", "overseers", "occupation", "interloper",
    "tremors", "small-business count", "board", "top officers", "percenter", "anti-Bork",
    "franchises", "solicitor", "businesswoman", "applicant", "attackers", "zombie",
    "lovebirds", "cop", "legions", "cyclists", "club", "volunteer",
    "bicyclist", "investor", "backpackers", "foundation bylaws", "junior", "nonconformists",
    "whizzes", "dwellers", "patrol", "ranger", "biker", "hiker",
    "pro", "this executive", "recent surveys", "junkies", "audience research", "businesspeople",
    "department policy", "rescuers", "ushers", "caretaker", "woman", "sensation",
    "direct-mail-mogul", "aerospace giant", "bloc", "hard-liner", "investment bankers", "graduate-student",
    "financial industry executives", "freaks", "cohorts", "co-developers", "one-person", "national statistics office",
    "prosecution", "litigants", "participant", "unanimously", "homeowner", "treasurers",
    "scavengers", "schemers", "market makers", "trading officials", "company spokeswoman", "dealer",
    "grateful traders", "industry data", "proxy material", "carpenters", "fast-food industry analysts", "endorsers",
    "an exchange spokesman", "vice president-finance", "lot", "low lifes", "bribed", "not-for-profit corporation",
    "case", "biochemist", "cabal", "assistant secretary of state", "organizations", "conservative legal theorists",
    "working groups", "plants", "investment managers", "pools", "transportation official", "salesparson",
    "evangelist", "general-director", "tossers", "broker-dealers", "government spokesman", "ministry statement",
    "educators and researchers", "waitress", "solicitors", "agency officials", "teenagers", "mass",
    "mob", "tot", "slopes", "dad", "sitter", "exploiter",
    "prodigy", "former president", "narcokleptocrat", "detectives", "scriptwriters", "scourge",
    "lobby", "biped", "traditionalist", "trio", "existentialist", "network executive",
    "co-publisher", "senators", "advertisers", "his staff", "councilman", "stickler",
    "populist", "co-editor", "co-workers", "bookkeeper", "ad executives", "freshman",
    "grandstander", "talk-show host", "teachers", "cheerleaders", "ninth graders", "these notes",
    "betrayer", "martyr", "recent academic research", "deadwood", "retailers", "sweetheart",
    "creditor", "super-user", "intruder", "quarry", "chaps", "spooks",
    "dealers", "analysts", "stewards", "spy-chaser", "program-trading executive", "unionist",
    "well-wishers", "alliance", "bond dealers", "that", "doctor", "ideologist",
    "that law", "trial referees", "underwriter", "interior decorator", "intellectual", "establishment",
    "hardliner", "pastor", "toxicologist", "circle", "do-gooders", "painters",
    "grandmothers", "housewife", "choir", "novice", "rally", "women's-rights",
    "convention", "polls", "under-secretary", "savers\/investors", "ex-accountant", "slave",
    "scribe", "pamphleteer", "segments", "segment", "chairman of", "employees of",
    "bulls", "industry executives", "he and others", "antagonists", "drummer", "industry watcher",
    "founders", "freeholders", "federal prosecutors", "mastermind", "two advisers", "financial advisers",
    "vocalist", "trend-setters", "die-hards", "technocrats", "laborer", "roughneck",
    "union leader", "subdirector", "decorators", "noblemen", "piker", "raptors",
    "wizards", "stock brokers", "tormentors", "manipulators", "arbs", "policy illustrations",
    "policyholder", "specialist there", "counselor", "chanteuse", "stiff", "bookers",
    "protector", "grandees", "syndicator", "authors", "stock-trader", "adversaries",
    "spokeman", "jockeys", "theologians", "money manager", "council research director", "pharaohs",
    "flunky", "film-makers", "", "right-wing", "interrogators", "podiatrist",
    "collector", "parliamentarian", "prime ministers", "auditor-general", "millionaires", "short sellers",
    "goblins", "unanimous court", "greenhouse theories", "tribes", "documents", "foreman",
    "his attorney", "roughnecks", "evangelist-industrialist", "right", "messiah", "press",
    "internal church documents", "fund-raisers", "presenter", "converts", "photographer", "opinion-makers",
    "whiner", "newcomer", "paralegal", "environmentalist", "director", "allrightniks",
    "roustabouts", "entrepreneurs", "electrician", "nine-months", "epileptics", "nation",
    "troublemakers", "repeaters", "neurologists", "mud-logger", "cook", "controller",
    "chief accounting officer", "attacker", "coward", "sister-in-law", "prude", "rapist",
    "assailant", "kinfolk", "industry executives and analysts", "then-husband", "private investigators", "management consultants",
    "vendors", "companies", "latest reports", "purchasing agents", "players", "technologist",
    "postmaster", "populace", "audiophiles", "eccentrics", "memorialist", "female",
    "lame duck", "detailsman", "government analyst", "scrambles", "chairman-elect", "contact",
    "uncles", "terrorist", "slingers", "management-consultant", "lyricist", "chums",
    "baker", "legitimately", "accuser", "embezzler", "opposition activists", "conscripts",
    "essayist", "stark numbers", "prime minister", "suvivors", "an embassy source", "sides",
    "flier", "purchaser", "hostage", "weakling", "sanitationists", "troop",
    "grandmasters", "builder", "human", "finance executive", "rights plan", "bean counters",
    "budgeteers", "pork-barrelers", "battlegroups", "joint chiefs", "companions", "postmaster general",
    "betters", "spendthrifts", "worriers", "lessers", "witch", "famous",
    "near famous", "matron", "name-dropper", "droppers", "fake", "neophytes",
    "bluebloods", "then-president", "quisling", "optimists", "pessimists", "market operators",
    "small-business lobbyists", "hot shot", "bankers", "dropper", "fraud", "pedagogue",
    "contemporaries", "virtuosos", "musician", "media", "oilman", "greenmailer",
    "instructor", "accompanist", "interpreter", "either party", "shopper", "manufacturer",
    "retailing observer", "editor-in-chief", "nephew", "tycoons", "self-starters", "insurance holding company",
    "corporate regulators", "peddler", "in-crowd", "congressman", "conservationists", "my conservative calculations",
    "knowledgeable individuals", "great-grandchildren", "black", "right-wingers", "fellas", "currency analysts",
    "backer", "manufacturers", "anemics", "co-chief executives", "disciples", "financial advisers",
    "an executive", "financial officer", "inventors", "draftsmen", "trafficker", "felons",
    "forger", "computer industry executive", "janitor", "art thieves", "receptionists", "deckhands",
    "independents", "delinquents", "cousins", "tipsters", "live-haulers", "processors",
    "evangelists", "hiders", "masons", "roofers", "payer", "deputy assistant commissioner",
    "man", "orthodoxy", "kidnappers", "captives", "ex-president", "analysts",
    "two-time-losers", "cable-TV industry executives", "legal observers", "chemist-turned-entrepreneur", "investment salesmen", "toddler",
    "newborns", "first-grader", "weather man", "benefactors", "savers", "reckons",
    "securities regulators", "amahs", "stepchildren", "four-man", "throwers", "self-employed",
    "actuary", "doubter", "citizenship", "brass", "dropout", "hairdresser",
    "manpower", "detractors", "bully", "whiz", "enthusiast", "both groups",
    "less-conservative magazines", "great-grandfather", "vice chairmen", "kingmaker", "alchemists", "spenders",
    "representives", "tribe", "top floor trader", "thrifts", "working poor", "commandos",
    "rustlers", "flag-burner", "assassin", "protester", "landscapers", "entrants",
    "industry experts", "donor", "mother-in-law", "retailer", "runners-up",
    "proprietor", "in-and-outer", "filberts", "intermediaries", "trust spokeswoman", "evil-doers",
    "astrophysicist", "jocks", "worker spokesman", "industry lawyers", "foreign bank analyst", "bank analysts",
    "masseuses", "acupuncturist", "yellows", "dignitaries", "auctioneer", "originators",
    "second ministry official", "person", "traders", "money launderers", "president judge", "grand-jury report",
    "grand jury report", "processor", "vegetarians", "another lawyer", "court employees", "jurists",
    "fixture", "best", "descendant", "trader", "exporters", "commandant",
    "agent", "gunner", "wag", "junkholders", "boats", "workman",
    "tenant", "arsonist", "ratepayers", "wealthy", "revolutionaries", "grandparents",
    "dealer-to-dealer", "autocrat", "super-rich", "affluent", "ranks", "crown prince",
    "drinker", "shopkeepers", "bureau spokesman", "pro-Gorbachev", "socialists", "pastors",
    "warrior", "comrade", "industry officials", "then-minister", "congressional aide", "patrols",
    "challengers", "suspect", "industrialist", "advice", "seekers", "pundits",
    "foe", "compatriots", "observers", "insurance brokers and executives", "partisans", "ambassadors",
    "then-Speaker", "mummies", "dancers", "syndicates", "biophysicist", "three-day-old",
    "two molecular biologists", "collectivizers", "objects", "collectives", "stooges", "naturalist",
    "lesbians", "fellows", "electorate", "co-founder", "pessimist", "guests",
    "bond market analysts", "navigator", "skipper", "victor", "sportsmen", "galleries",
    "an international economist", "people", "scribes", "columnists", "pervert", "hacks",
    "sarakin", "lawmakers", "emissaries", "computer-software", "observer", "monitors",
    "bear", "administrator general", "despots", "treasury secretaries", "potentates", "frogmen",
    "ayatollah", "secretary", "quarterbacks", "culprit", "proxy statement", "vice",
    "executive officers", "senior administration officials", "most analysts", "infant", "geneticist", "biologist",
    "biologists", "currencny analysts", "longshoreman", "market sources", "hackers", "central bank governor",
    "boatload", "warriors", "revelers", "director-general", "policymaker", "grandson",
    "airport officals", "floor trader", "futures trader", "union", "of individuals", "another individual",
    "writer\/producers", "designate", "pol", "bombshell", "villains", "subversives",
    "corpse", "lifeguards", "nun", "clerics", "congregation", "bell-ringer",
    "bellringers", "male", "complexities", "collaborators", "emperor", "avant-garde",
    "editors", "prize-fighter", "rules", "state official", "lead manager", "portfolio managers",
    "airline", "an airport spokesman", "mutual-fund managers", "five-member", "harbor", "",
    "those who", "liars", "poohbah", "parishioners", "church-goers", "octogenarians",
    "athletes", "newsies", "hands", "this official", "senior aide", "rating concerns",
    "workforce", "this", "clergy", "company and city officials", "deputy chief executive", "market players",
    "industry observers", "both companies", "tire-kickers", "lookee-loos", "pressman", "investment advisers",
    "pitchmen", "deputy chairman", "network", "clerk-turned", "tyke", "following",
    "excutives", "bargain-hunters", "high rollers", "con artists", "gullible", "greedy",
    "indictment", "low-lifes", "which", "telemarketers", "deputy chief", "colonists",
    "member", "locals", "lender", "investment banker", "screenwriters", "queers",
    "homosexual", "of them", "nationals", "lonely", "armies", "stations",
    "another trader", "reports", "contender", "shoo-in", "prime minister", "manufacturers and foreign buyers",
    "these couriers", "airmen", "even pro-union pilots", "union study", "story", "co-pilot",
    "hires", "dispatchers", "vet", "expert", "post-Barre", "cocotte",
    "conductor", "lump", "maestro", "courtesan", "minor", "fairy",
    "compatriot", "bass", "soprano", "ex-wife", "glitterati", "hand",
    "workaholic", "deputy chief of staff", "slate", "co-defendant", "patriot", "page",
    "pseudo-lobbyists", "mogul", "dancer", "spirits", "waif", "jugglers",
    "magicians", "hustlers", "traitor", "thugs", "curse", "film maker",
    "fighters", "sympathizers", "impersonator", "watchman", "options exchange officials", "tramp",
    "royalty", "pianist-comedian", "escort", "busloads", "schoolboys", "dummies",
    "execs", "schoolmates", "gentry", "servant", "security", "soft-spoken clarinetist",
    "cellists", "pianist\/bassoonist\/composer", "bassist", "improviser", "oboist", "presenters",
    "biographer", "convention-goers", "rider", "bank holding company", "newsman", "investment managers",
    "brewer", "borrower", "defaulters", "dishonesty", "subject", "two judges",
    "academic", "strongman", "outfielders", "centerfielder", "first baseman", "mates",
    "best-pitcher", "news reports", "broadcasters", "lanzador", "surfers", "federal researchers",
    "epidemiologist", "machine tool builders", "machine tool producer", "paper", "fiancee", "novitiate",
    "malefactors", "ruler", "friar", "superior", "pimps", "transvestites",
    "rockers", "types", "opportunist", "unfortunate victim", "progenitors", "licensee",
    "pharmacists", "grand marshal", "crowds", "message", "physician-executive", "machine tool makers",
    "dealmakers", "initiatiors", "revised industry forecasts", "incumbents", "mainlander", "therapists",
    "bodyworkers", "nine-member", "hopeful", "carriers", "finance director", "ex-chief executive",
    "duke", "secretary of state", "school", "hunter", "maharajahs", "siblings",
    "hawkers", "antihero", "cowards", "hypocrites", "addict", "pauper",
    "charlatans", "internationalists", "sheiks", "cripple-maker", "beggars", "card shark",
    "prostitute", "market researchers", "legislation", "specialists", "other analysts", "extremist",
    "maniac", "takers", "anchorman", "landlord", "extras", "unknowns",
    "vice president\/product", "vice president\/national-government", "brokerage house officials", "art gallery", "market analysts", "news service reports",
    "chief marketing officer", "comic", "co-sponsor", "receiver", "confreres", "transportation department spokesman",
    "other officials", "chancellor of exchequer", "coterie", "deputy prime minister", "immunologist", "personal computer maker",
    "ice-baggers", "scalawags", "opportunists", "knowledgeable individual", "unionists", "district attorney",
    "attorney-consultant", "politico-plaintiffs", "soulmates", "network officials", "ex-hurler", "rooters",
    "favorites", "septuagenarian", "shortstop", "co-hero", "vote-getters", "thrift",
    "ex-employees", "commented", "panelists", "cranks", "soreheads", "he and other traders",
    "industry officials", "veteran scientists", "financeer", "doormen", "provost", "venture capitalists",
    "mentors", "latter", "statisticians", "wags", "attorney",
    "options industry officials", "co-chairmen", "pomologist", "court watchers", "gunners", "commander in chief",
    "behemoths", "creatures", "mailmen", "anchors", "devotees", "librarians",
    "cynic", "market participants", "centurions", "gamblers", "knights", "clowns",
    "snowbirds", "tourist", "expansionists", "anti-heroes", "mafiosi", "non-lawyers",
    "punchers", "his notes", "pitcher-coach", "catchers", "righthander", "stopper",
    "sage", "interventionists", "observer", "priests", "experts",
    "chief strategic officer", "prey", "money", "casualty", "foil", "jester",
    "bubblelike", "dummy", "airline analysts", "chairman", "unifier", "peacemaker",
    "jogger", "teens", "pols", "most accounts", "city officials", "barons",
    "buster", "enigma", "board members", "shifting", "dons", "city official",
    "ideologues", "pragmatists", "councilwoman", "leaguers", "minor-leaguer", "scapegoat",
    "mistress", "coup-makers", "cadet", "spy-in-training", "leftists", "gringos",
    "sergeants", "rent-a-colonel", "pal", "recruit", "intelligence officials", "half-brother",
    "cadets", "former intelligence official", "super-spy", "mistresses", "reforms", "elderly people",
    "ironfist", "hunter-gatherers", "veterinarians", "protectors", "banking company", "senior executive",
    "kiddies", "near greats", "great", "retiree", "counselors", "trade sources",
    "document", "anti-Noriega", "doomsayer", "jurist", "hostilities", "artillerists",
    "recipient", "creditors", "also-ran", "chief of staff", "ex-Marine", "fancy'shvartzer",
    "anti-white", "attorneys", "inmate", "their conversation", "monsieur", "attendee",
    "conventioners", "novitiates", "virgins", "pilote", "farmwives", "idiots",
    "murderers", "vagabonds", "messengers", "sexes", "refusers", "songwriters",
    "duffers", "gendarme", "guinea pig", "primitives", "surgeon", "heroine",
    "professional", "sheriffs", "reinforcements", "craftsmen", "amateurs", "assistant director",
    "cryptographers", "conference speakers", "speaker", "curators", "semi-celebrities", "scientist",
    "government minister", "cardholders", "advocates", "loonies", "bullfighter", "showgirls",
    "guest", "lead", "viewer", "statesmen", "arborists", "orchardists",
    "rosarians", "barbers", "adventure", "these people", "specialist", "exchange",
    "hobos", "exorcist", "priest", "entourage", "letter",
    "tax-collecting agency", "anti-abortionist", "retail sales report", "household", "appraisers", "restorer",
    "workmen", "merchant", "phalanx", "demons", "demonologist", "psychics",
    "magician", "her", "obstructionist", "preparer", "imperialists", "",
    "money manager", "second money manager", "industry observers", "witches", "debtors", "schoolteachers",
    "truant", "pupils", "less gifted", "state officials", "securities commissioners", "generalist",
    "generalists", "litigator"


]

temp_list = []
for sources in desired_checklist_of_anonymous_sources:
    if sources not in ['they', 'for']:
        for source in sources.split(' and '):
            if source.startswith('the '):
                source = source[len('the '):]
            if source.startswith('a '):
                source = source[len('a '):]
            if source.endswith('s'):
                temp_list.append(source[:-1])
            temp_list.append(source)

desired_checklist_of_anonymous_sources = list(set(temp_list))
desired_checklist_of_anonymous_sources = sorted(desired_checklist_of_anonymous_sources, key=lambda x: -len(x))



desired_checklist_of_anonymous_sources = sorted(desired_checklist_of_anonymous_sources, key=lambda x: -len(x))


desired_checklist_of_documents = [
    "bill", "the washington post", "the associated press", "reuters",
    "poll", "report", "associated press", "polls",
    "study", "local media", "reports", "nbc news",
    "national poll", "article", "state television", "the cincinnati enquirer",
    "intergovernmental panel on climate change", "science", "stock market", "weekly newspaper",
    "white house fact sheet", "the sun", "united states federal aviation administration", "every list",
    "taizhou city environmental protection association", "news reports", "new york times investigation",
    "the chicago tribune",
    "chinese legislature", "prop . 22", "uber", "scientific studies",
    "california voters", "orlando sentinel", "law", "aaj tak television news channel",
    "pennsylvania poll", "the press trust of india news agency", "the gainesville sun", "china national radio",
    "sunderland", "cbs news", "lyft", "the national oceanic and atmospheric administration",
    "fivethirtyeight", "research", "washington post", "dossier",
    "kansas voters", "models", "climate home", "news agency",
    "the los angeles times", "tod hileman", "indonesian news media", "the hutchinson news",
    "amarillo globe", "local news outlets", "meteorological data", "forecast",
    "card industry bloggers", "most accounts", "xinhua news", "henan business daily",
    "local media reports", "kompas newspaper", "the intermediate people ’s court", "the lao news agency",
    "official document", "the weather channel", "mexican television", "the indianapolis star",
    "oregon state senate", "the oregonian", "oregon's house", "vermont senate judiciary committee",
    "seven days", "coroner's report", "the pittsburgh post", "government investigators",
    "draft", "james b. comey", "survey", "rod j. rosenstein",
    "bari weiss", "media reports", "voters", "nbc / surveymonkey",
    "wikileaks", "vox", "face the nation", "the new york times",
    "hurricane records", "records", "analysis", "asia development bank",
    "xinhua", "internal report", "indian news channel ndtv", "the soma mining company",
    "the anadolu news agency", "turkish media", "penal code", "caucasus barometer",
    "abc radio melbourne", "local news reports", "rtv", "tempo.co",
    "pediatrics statement", "texas regulations", "plain view project", "tennessee regulations",
    "nasa", "cnbc's \"squawk box\"", "the national bureau of statistics", "cnn",
    "campaign finance data", "internal bp documents", "vote", "petition",
    "new america", "database", "doordash"
]


desired_checklist_of_documents = sorted(desired_checklist_of_documents, key=lambda x: -len(x))

ner_filter_list = [
    'PERSON',
    'NORP',
    'ORG',
    'GPE',
    'LAW',
]