#!/bin/sh

# add all the jars anywhere in the lib/ directory to our classpath
here=$(dirname $0)
CLASSES=$here/bin
CLASSES=$CLASSES:$(echo $here/lib/*.jar | tr ' ' :)
CLASSES=$CLASSES:$here/narrative.jar

echo "COMMAND: java.exe -XX:ParallelGCThreads=2 -Xmx3000m -Xms3000m -ea -classpath $CLASSES $*"
java.exe -XX:ParallelGCThreads=2 -Xmx3000m -Xms3000m -ea -classpath $CLASSES $*

####### intellij generated script

java.exe -XX:ParallelGCThreads=2 -Xmx3000m \
	-classpath "C:\Users\alexa\Projects\usc-research\source-exploration\models\ACL2013_Personas\java\out\production\java;\
				C:\Users\alexa\Projects\usc-research\source-exploration\models\ACL2013_Personas\java\lib\*" \
		personas.ark.cs.cmu.edu.PersonaModel \
				movies.properties
