orig_speaking_lexicon = [
    'say', 'says', 'said', 'saying',
    'echo', 'echoes', 'echoed',
    'tell', 'told',
    'added', 'adds', 'adding',
    'describe', 'describes', 'described',
    'claims', 'claims', 'claimed',
    'explained', 'explains', 'explain',
    'mentioned', 'mentions', 'mention',
    'articulated', 'articulates', 'articulate',
    'called', 'calls', 'call',
    'declared', 'declares', 'declare',
    'worried', 'worries', 'worry',
    'asserted', 'asserts', 'assert',
    #
    'write', 'writes', 'wrote',
]

polinear_speaking_lexicon = [
    # discovered via the polnear corpus
    "accused", "accuses", "accusing",
    "acknowledge", "acknowledged", "acknowledges", "acknowledging",
    "added", "adding", "adds",
    "admits", "admitted", "admitting",
    "adopted",
    "advice", "advising", "advised",
    "agree", "agreed", "agrees",
    "allegations", "alleged", "alleging",
    "allowed", "allows",
    "among",
    "announce", "announced", "announcement", "announces", "announcing",
    "answered",
    "appear", "appeared", "appears", "applauded",
    "approved",
    "argue", "argued", "argues", "arguing", "argument",
    "articulated",
    "ask", "asked", "asking", "asks",
    "assailed",
    "asserted", "asserting",
    "assured", "assures",
    "attacked", "attacking",
    "attributed",
    "back", "backed", "backing", "backs",
    "believe", "believed", "believes", "believing",
    "bemoaned",
    "blame", "blamed", "blames", "blaming",
    "blast", "blasted", "blasting", "blasts",
    "blocked", "blocks", "boasted",
    "by",
    "call", "called", "calling", "calls",
    "captured",
    "cast",
    "cautioned",
    "celebrated",
    "challenged",
    "chanted", "chanting", "chants",
    "charged",
    "cheered",
    "cite", "cited", "cites", "citing",
    "claim", "claimed", "claiming", "claims",
    "coined",
    "comment",
    "compared",
    "complained", "complains", "complaints",
    "conceded", "concedes",
    "concerns",
    "concluded", "concludes",
    "condemned",
    "confirmed",
    "consider", "considered", "considering", "considers",
    "contends",
    "continued", "continued",
    "convey",
    "convince",
    "counts",
    "covered",
    "criticism", "criticized", "criticizing",
    "decide", "decided", "decision",
    "declared", "declares", "declaring",
    "declined",
    "decried",
    "deemed",
    "defend", "defended", "defending", "defends",
    "delivered",
    "demanded", "demands",
    "denied",
    "denounced", "denouncing",
    "derided",
    "described", "describes", "describing",
    "designed",
    "determined",
    "disclosed",
    "discovered",
    "discussed", "discussing",
    "dismissed", "dismisses", "dismissing",
    "documented", "documents",
    "doubt",
    "downplayed",
    "drew",
    "dubbed",
    "echoed",
    "emailed",
    "emphasized", "emphasizing",
    "encouraged", "encouraging",
    "endorsed", "endorses",
    "envision", "envisions",
    "estimate", "estimated", "estimates",
    "eviscerated",
    "expect", "expected", "expecting", "expects",
    "explained", "explaining", "explains",
    "exposed",
    "expressed",
    "favor", "favored", "favors",
    "fear", "feared", "fearing", "fears",
    "features",
    "feel", "felt",
    "filed",
    "find",
    "finds",
    "found",
    "gave",
    "guess",
    "highlighted",
    "hired",
    "hope", "hoped", "hopes", "hoping",
    "identified",
    "ignored",
    "implied",
    "included", "includes",
    "indicate", "indicated", "indicates",
    "informed",
    "insist", "insisted", "insisting", "insists",
    "introduced",
    "invoked",
    "issued",
    "joked",
    "knocked",
    "knew", "know", "known", "knows",
    "labeled",
    "lamented",
    "learned",
    "legalized",
    "letting",
    "like", "liked", "likened",
    "listed", "listing", "lists",
    "look", "looked", "looks",
    "loved", "loves",
    "made",
    "mean",
    "mentioned", "mentioning",
    "mocked", "mocking", "mocks",
    "named",
    "news",
    "nominated",
    "note", "noted", "notes", "noting",
    "observed",
    "offered", "offering", "offers",
    "opponent", "oppose", "opposed", "opposes",
    "ordered",
    "outline", "outlined",
    "painting",
    "passed",
    "perceived",
    "plan", "planned", "plans",
    "pledged", "pledges", "pledging",
    "plot",
    "portrayed",
    "posted",
    "praised", "praises", "praising",
    "predict", "predicted",
    "prefer", "preferred", "prefers",
    "presented",
    "pressed",
    "projected",
    "promise", "promised", "promises", "promising",
    "promoting", "prompting",
    "proposal", "proposed", "proposes",
    "protested",
    "provided",
    "published",
    "push", "pushed",
    "put",
    "question", "questioned", "questioning", "questions",
    "quoted", "quotes",
    "raised",
    "rattled",
    "read", "reads",
    "reaffirmed",
    "realized",
    "rebuts",
    "recalled", "recalling",
    "recited",
    "recognize", "recognized", "recognizing",
    "recommended",
    "recounted",
    "referenced", "referencing",
    "referring",
    "refusal", "refuse", "refused", "refuses", "refusing",
    "reiterated",
    "rejected", "rejecting", "rejects",
    "released",
    "remarked", "remarking",
    "remember", "remembered", "remembering", "remembers",
    "reminded", "reminding", "reminds",
    "repeated", "repeating",
    "replied",
    "reported", "reportedly", "reports",
    "requested", "requests",
    "require", "requires", "requiring",
    "resent",
    "responded", "responds",
    "restricting",
    "retweeted",
    "reveal", "revealed", "reveals",
    "ruled",
    "satirizing",
    "saw",
    "see",
    "seek", "seeking", "seeks",
    "seem", "seemed", "seemingly", "seems",
    "seen", "sees",
    "sense",
    "shared",
    "shouted",
    "show", "showed", "showing", "shows",
    "signed",
    "slammed", "slamming", "slams",
    "sought",
    "sounded",
    "speculation",
    "spoke",
    "stated", "states", "stating",
    "stressed",
    "sued",
    "suggest", "suggested", "suggesting", "suggests",
    "support", "supported", "supporter", "supporters", "supporting", "supports",
    "suspect",
    "tackles",
    "talked", "tell", "telling", "tells",
    "thanked",
    "think", "thinks", "thought",
    "threatened", "threatening",
    "titled",
    "told",
    "touted", "touting", "touts",
    "tweeted", "tweeting",
    "under",
    "underplays",
    "understood",
    "unveiled",
    "urged", "urges", "urging",
    "used",
    "view", "viewed", "views",
    "voided",
    "voted",
    "vow", "vowed", "vowing", "vows",
    "want", "wanted", "wants",
    "warn", "warned", "warning", "warns",
    "watched",
    "welcomed",
    "willing",
    "wondered",
    "worried", "worries", "worry",
    "would",
    "write", "writes", "writing", "written", "wrote",
    "yelled",
]

full_speaking_lexicon = orig_speaking_lexicon + polinear_speaking_lexicon

orig_ner_list = [
    'PERSON'
]

polinear_ner_list = [
    'NORP',
    'ORG',
    'GPE',
    'LAW',
]

full_ner_list = orig_ner_list + polinear_ner_list

multiword_phrases_present_tense = [
    'according to', 'points out', 'calls for', 'tells me', 'calls on', 'points to', 'asks about',
    'refers to', 'makes it clear', 'focuses on', 'vows to', 'argues for', 'talks about'
]

multiword_phrases_past_tense = [
    'pointed out', 'called for', 'told me', 'called on', 'pointed to', 'asked about',
    'referred to', 'made it clear', 'focused on', 'vowed to', 'argued for', 'talked about'
]

desired_checklist_of_anonymous_sources = [
    # anonymous sources/groups of sources
    "officials", "experts", "analysts", "scientists", "economists", "authorities", "critics", "environmentalists",
    "person", "woman", "forecasters", "witnesses", "prosecutors", "spokeswoman", "rights groups",
    "government scientists", "people", "investigators", "officers", "administration officials", "police",
    "associated press reporter", "opponents", "proponents", "opponents", "oil experts",
    "spokeswoman", "european scientists", "local news media", "surrogates", "restaurant", "person", "employee",
    "women", "four people", "lauren bonner", "pilot", "several people", "another man", "one man", "city officials",
    "unnamed", "administration official", "mississippi official", "witnesses", "officials", "election officials",
    "israel", "republicans", "kansas officials", "local residents", "weather officials", "company insiders",
    "climate change denialists", "they", "union officials", "local ’s boss", "scientists", "local media outlets",
    "opposition", "a higher education trade group", "government officials; asiana officials",
    "head of the vote auditing company", "researchers", "protesters", "readers", "both sides", "new england ’s seafood industry",
    "insurance companies", "speculation", "auditors", "conservative media outlets", "safety experts", "proponents",
    "native americans and environmental activists", "protestors", "legal experts", "government ’s statistics bureau",
    "robstown police officials", "bill's sponsors", "white house officials", "letter", "environmental groups",
    "white house officials", "developers", "representative", "puerto rico electric power authority",
    "company officials", "company official and four crew members", "salvage experts", "engineers", "italian news media",
    "a pentagon spokeswoman", "television interview", "many brazilians", "european leaders", "customers",
    "taciturn fishermen", "television news", "environmental activists", "native american leaders", "for-profit sector",
    "consumer protection advocates", "organizers", "demonstrators", "local prosecutor ’s office", "cbs staff member",
    "cbs staff members", "spokesman", "cbs executives", "officials", "nagashiki shipping representative",
    "the mauritian authorities", "political opponents", "political rivals", "policy makers", "police spokeswoman",
    "israeli security officials", "dispatcher", "federal government", "gun salesman", "sellers", "a gun owner",
    "enthusiasts", "dealers", "defenders", "advocates", "lawyer", "activists", "neighbor", "diplomats",
]

desired_checklist_of_documents = [
    # documents
    "bill", "report", "state television", "local media", "study", "reuters", "associated press",
    "new york times investigation", "white house fact sheet", "the sun",
    "united states federal aviation administration", "every list", "news reports", "the lao news agency",
    "the chicago tribune", "weekly newspaper", "the soma mining company", "the anadolu news agency", "turkish media",
    "science", "sunderland", "caucasus barometer", "card industry bloggers", "forecast", "meteorological data",
    "the associated press", "local news outlets", "amarillo globe", "the hutchinson news", "tod hileman", "nbc news",
    "cbs news", "the los angeles times", "climate home", "models", "penal code", "local news reports", "polls",
    "abc radio melbourne", "records", "intergovernmental panel on climate change", "the cincinnati enquirer",
    "the washington post", "media reports", "the weather channel", "draft", "government investigators",
    "the cincinnati enquirer", "seven days", "vermont senate judiciary committee", "oregon's house", "the oregonian",
    "oregon state senate", "the indianapolis star", "analysis", "survey", "asia development bank", "plain view project",
    "database", "new america", "internal bp documents", "cnbc's \"squawk box\"",
    "intergovernmental panel on climate change", "nasa", "the national oceanic and atmospheric administration",
    "pediatrics statement", "tempo.co", "dossier",
]