orig_speaking_lexicon = [
    'say', 'says', 'said', 'saying',
    'echo', 'echoes', 'echoed',
    'tell', 'told',
    'added', 'adds', 'adding',
    'describe', 'describes', 'described',
    'claims', 'claims', 'claimed',
    'explained', 'explains', 'explain',
    'mentioned', 'mentions', 'mention',
    'articulated', 'articulates', 'articulate',
    'called', 'calls', 'call',
    'declared', 'declares', 'declare',
    'worried', 'worries', 'worry',
    'asserted', 'asserts', 'assert',
    #
    'write', 'writes', 'wrote',
]

polinear_speaking_lexicon = [
    # discovered via the polnear corpus
    "accused", "accuses", "accusing",
    "acknowledge", "acknowledged", "acknowledges", "acknowledging",
    "added", "adding", "adds",
    "admits", "admitted", "admitting",
    "adopted",
    "advice", "advising", "advised",
    "agree", "agreed", "agrees",
    "allegations", "alleged", "alleging",
    "allowed", "allows",
    "among",
    "announce", "announced", "announcement", "announces", "announcing",
    "answered",
    "appear", "appeared", "appears", "applauded",
    "approved",
    "argue", "argued", "argues", "arguing", "argument",
    "articulated",
    "ask", "asked", "asking", "asks",
    "assailed",
    "asserted", "asserting",
    "assured", "assures",
    "attacked", "attacking",
    "attributed",
    "back", "backed", "backing", "backs",
    "believe", "believed", "believes", "believing",
    "bemoaned",
    "blame", "blamed", "blames", "blaming",
    "blast", "blasted", "blasting", "blasts",
    "blocked", "blocks", "boasted",
    "by",
    "call", "called", "calling", "calls",
    "captured",
    "cast",
    "cautioned",
    "celebrated",
    "challenged",
    "chanted", "chanting", "chants",
    "charged",
    "cheered",
    "cite", "cited", "cites", "citing",
    "claim", "claimed", "claiming", "claims",
    "coined",
    "comment",
    "compared",
    "complained", "complains", "complaints",
    "conceded", "concedes",
    "concerns",
    "concluded", "concludes",
    "condemned",
    "confirmed",
    "consider", "considered", "considering", "considers",
    "contends",
    "continued", "continued",
    "convey",
    "convince",
    "counts",
    "covered",
    "criticism", "criticized", "criticizing",
    "decide", "decided", "decision",
    "declared", "declares", "declaring",
    "declined",
    "decried",
    "deemed",
    "defend", "defended", "defending", "defends",
    "delivered",
    "demanded", "demands",
    "denied",
    "denounced", "denouncing",
    "derided",
    "described", "describes", "describing",
    "designed",
    "determined",
    "disclosed",
    "discovered",
    "discussed", "discussing",
    "dismissed", "dismisses", "dismissing",
    "documented", "documents",
    "doubt",
    "downplayed",
    "drew",
    "dubbed",
    "echoed",
    "emailed",
    "emphasized", "emphasizing",
    "encouraged", "encouraging",
    "endorsed", "endorses",
    "envision", "envisions",
    "estimate", "estimated", "estimates",
    "eviscerated",
    "expect", "expected", "expecting", "expects",
    "explained", "explaining", "explains",
    "exposed",
    "expressed",
    "favor", "favored", "favors",
    "fear", "feared", "fearing", "fears",
    "features",
    "feel", "felt",
    "filed",
    "find",
    "finds",
    "found",
    "gave",
    "guess",
    "highlighted",
    "hired",
    "hope", "hoped", "hopes", "hoping",
    "identified",
    "ignored",
    "implied",
    "included", "includes",
    "indicate", "indicated", "indicates",
    "informed",
    "insist", "insisted", "insisting", "insists",
    "introduced",
    "invoked",
    "issued",
    "joked",
    "knocked",
    "knew", "know", "known", "knows",
    "labeled",
    "lamented",
    "learned",
    "legalized",
    "letting",
    "like", "liked", "likened",
    "listed", "listing", "lists",
    "look", "looked", "looks",
    "loved", "loves",
    "made",
    "mean",
    "mentioned", "mentioning",
    "mocked", "mocking", "mocks",
    "named",
    "news",
    "nominated",
    "note", "noted", "notes", "noting",
    "observed",
    "offered", "offering", "offers",
    "opponent", "oppose", "opposed", "opposes",
    "ordered",
    "outline", "outlined",
    "painting",
    "passed",
    "perceived",
    "plan", "planned", "plans",
    "pledged", "pledges", "pledging",
    "plot",
    "portrayed",
    "posted",
    "praised", "praises", "praising",
    "predict", "predicted",
    "prefer", "preferred", "prefers",
    "presented",
    "pressed",
    "projected",
    "promise", "promised", "promises", "promising",
    "promoting", "prompting",
    "proposal", "proposed", "proposes",
    "protested",
    "provided",
    "published",
    "push", "pushed",
    "put",
    "question", "questioned", "questioning", "questions",
    "quoted", "quotes",
    "raised",
    "rattled",
    "read", "reads",
    "reaffirmed",
    "realized",
    "rebuts",
    "recalled", "recalling",
    "recited",
    "recognize", "recognized", "recognizing",
    "recommended",
    "recounted",
    "referenced", "referencing",
    "referring",
    "refusal", "refuse", "refused", "refuses", "refusing",
    "reiterated",
    "rejected", "rejecting", "rejects",
    "released",
    "remarked", "remarking",
    "remember", "remembered", "remembering", "remembers",
    "reminded", "reminding", "reminds",
    "repeated", "repeating",
    "replied",
    "reported", "reportedly", "reports",
    "requested", "requests",
    "require", "requires", "requiring",
    "resent",
    "responded", "responds",
    "restricting",
    "retweeted",
    "reveal", "revealed", "reveals",
    "ruled",
    "satirizing",
    "saw",
    "see",
    "seek", "seeking", "seeks",
    "seem", "seemed", "seemingly", "seems",
    "seen", "sees",
    "sense",
    "shared",
    "shouted",
    "show", "showed", "showing", "shows",
    "signed",
    "slammed", "slamming", "slams",
    "sought",
    "sounded",
    "speculation",
    "spoke",
    "stated", "states", "stating",
    "stressed",
    "sued",
    "suggest", "suggested", "suggesting", "suggests",
    "support", "supported", "supporter", "supporters", "supporting", "supports",
    "suspect",
    "tackles",
    "talked", "tell", "telling", "tells",
    "thanked",
    "think", "thinks", "thought",
    "threatened", "threatening",
    "titled",
    "told",
    "touted", "touting", "touts",
    "tweeted", "tweeting",
    "under",
    "underplays",
    "understood",
    "unveiled",
    "urged", "urges", "urging",
    "used",
    "view", "viewed", "views",
    "voided",
    "voted",
    "vow", "vowed", "vowing", "vows",
    "want", "wanted", "wants",
    "warn", "warned", "warning", "warns",
    "watched",
    "welcomed",
    "willing",
    "wondered",
    "worried", "worries", "worry",
    "would",
    "write", "writes", "writing", "written", "wrote",
    "yelled",
]

full_speaking_lexicon = orig_speaking_lexicon + polinear_speaking_lexicon

orig_ner_list = [
    'PERSON'
]

polinear_ner_list = [
    'NORP',
    'ORG',
    'GPE',
    'LAW',
]

full_ner_list = orig_ner_list + polinear_ner_list

multiword_phrases_present_tense = [
    'according to', 'points out', 'calls for', 'tells me', 'calls on', 'points to', 'asks about',
    'refers to', 'makes it clear', 'focuses on', 'vows to', 'argues for', 'talks about'
]

multiword_phrases_past_tense = [
    'pointed out', 'called for', 'told me', 'called on', 'pointed to', 'asked about',
    'referred to', 'made it clear', 'focused on', 'vowed to', 'argued for', 'talked about'
]

desired_checklist_of_anonymous_sources = [
    # anonymous sources/groups of sources
    "officials", "experts", "authorities", "analysts",
    "scientists", "forecasters", "critics", "person",
    "democrats", "opponents", "police", "woman",
    "spokesman", "spokeswoman", "economists", "witnesses",
    "legal experts", "rights groups", "officers", "prosecutors",
    "pilot", "environmentalists", "administration officials", "people",
    "government scientists", "investigators", "neighbor", "plaintiffs",
    "environmental groups", "residents", "white house officials", "proponents",
    "environmental activists", "retailers", "iowa couple", "uber driver",
    "villagers", "volunteer", "a higher education trade group", "gun control groups",
    "gun rights advocates", "mining watchdog groups", "starbucks spokesman", "target spokeswoman",
    "gun control experts", "local media outlets", "israel", "provincial environmental officials",
    "marianne williamson's state director", "supporters", "local ’s boss", "researchers",
    "kathleen sgamma", "oil experts", "taciturn fishermen", "mississippi official",
    "auditors", "television news", "speculation", "insurance companies",
    "reports", "fed policy makers", "big creek residents", "new england ’s seafood industry",
    "both sides", "readers", "protesters", "environmental officials",
    "union officials", "transit officials", "some workers", "election officials",
    "european scientists", "local news media", "restaurant", "employee",
    "white house official", "other men", "head of the vote auditing company", "some men",
    "companies", "kenya's top politicians", "justice department", "taxi companies",
    "news reports", "opposition", "lawmakers", "seismologists",
    "associated press reporter", "the city manager", "they", "company insiders",
    "weather officials", "kansas officials", "republicans", "local residents",
    "party official", "retired lawyer", "climate change denialists", "government officials",
    "fireman", "enza", "a republican operative", "surrogates",
    "local officials", "developers", "meteorologists", "defenders",
    "dealers", "enthusiasts", "a gun owner", "sellers",
    "gun salesman", "federal government", "dispatcher", "party strategists",
    "one house republican", "other republican", "climate experts", "global carbon project",
    "engineers", "911 recording", "advocates", "defendents lawyer",
    "salvage experts", "facebook spokewoman", "letter", "representative",
    "bill's sponsors", "robstown police officials", "government ’s statistics bureau",
    "puerto rico electric power authority",
    "company official and four crew members", "activists", "protestors", "native americans and environmental activists",
    "native american leaders", "for", "consumer protection advocates", "organizers",
    "election experts", "colleague of reid hoffman", "italian news media", "another man",
    "many brazilians", "photojournalist", "administration official", "unnamed",
    "city officials", "one man", "several people", "chinese court",
    "polk county sheriff ’s office spokeswoman", "european leaders", "lauren bonner", "four people",
    "women", "customers", "senior official", "television interview",
    "israeli security officials", "nagashiki shipping representative", "a pentagon spokeswoman", "police spokeswoman",
    "policy makers", "political rivals", "political opponents", "the mauritian authorities",
    "cbs executives", "safety experts", "conservative media outlets", "cbs staff members",
    "cbs staff member", "local prosecutor ’s office", "demonstrators", "company officials",
    "asiana officials"
]

desired_checklist_of_documents = [
    "bill", "the washington post", "the associated press", "reuters",
    "poll", "report", "associated press", "polls",
    "study", "local media", "reports", "nbc news",
    "national poll", "article", "state television", "the cincinnati enquirer",
    "intergovernmental panel on climate change", "science", "stock market", "weekly newspaper",
    "white house fact sheet", "the sun", "united states federal aviation administration", "every list",
    "taizhou city environmental protection association", "news reports", "new york times investigation",
    "the chicago tribune",
    "chinese legislature", "prop . 22", "uber", "scientific studies",
    "california voters", "orlando sentinel", "law", "aaj tak television news channel",
    "pennsylvania poll", "the press trust of india news agency", "the gainesville sun", "china national radio",
    "sunderland", "cbs news", "lyft", "the national oceanic and atmospheric administration",
    "fivethirtyeight", "research", "washington post", "dossier",
    "kansas voters", "models", "climate home", "i",
    "the los angeles times", "tod hileman", "indonesian news media", "the hutchinson news",
    "amarillo globe", "local news outlets", "meteorological data", "forecast",
    "card industry bloggers", "most accounts", "xinhua news", "henan business daily",
    "local media reports", "kompas newspaper", "the intermediate people ’s court", "the lao news agency",
    "official document", "the weather channel", "mexican television", "the indianapolis star",
    "oregon state senate", "the oregonian", "oregon's house", "vermont senate judiciary committee",
    "seven days", "coroner's report", "the pittsburgh post", "government investigators",
    "draft", "james b. comey", "survey", "rod j. rosenstein",
    "bari weiss", "media reports", "voters", "nbc / surveymonkey",
    "wikileaks", "vox", "face the nation", "the new york times",
    "hurricane records", "records", "analysis", "asia development bank",
    "xinhua", "internal report", "indian news channel ndtv", "the soma mining company",
    "the anadolu news agency", "turkish media", "penal code", "caucasus barometer",
    "abc radio melbourne", "local news reports", "rtv", "tempo.co",
    "pediatrics statement", "texas regulations", "plain view project", "tennessee regulations",
    "nasa", "cnbc's \"squawk box\"", "the national bureau of statistics", "cnn",
    "campaign finance data", "internal bp documents", "vote", "petition",
    "new america", "database", "doordash"
]